[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "https://github.com/:splat"
  status = 200

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/aa"
  to = "/index.html"
  status = 200
